###########################################################################################################
## A note about folder mapping: Your download client (sabnzbd, nzbget, etc) should be mapped in Docker   ##
## to the same path as your Servarr apps. If not,  files won't transfer properly after unpacking.        ##
## (e.g.: download client mapping: /host/media/folder:/media;                                            ##  
## Servarr app mapping: /host/servarr/folder:/media)                                                     ##
###########################################################################################################

version: "3"
services:
####  GLUETUN  ####
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn # or wireguard
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=United States
      - OBFUSCATED=enable
    networks:
      - name_of_your_network
      
####  SONARR: Port 8989  ####

  sonarr:
    image: ghcr.io/hotio/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID} #This can be optained with the following command: id -u
      - PGID=${PGID}
      - TZ=[Your_timezone] #A list of timezones can be found here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones. You will need to choose the one under "TZ identifier"
    volumes:
      - /path/to/your/config/folder:/config
      - /path/to/your/tv/files:/media/tv
      - /path/to/downloadclient-downloads:/downloads  
    depends_on:
      - gluetun
    network_mode: "container:gluetun"
    restart: unless-stopped
    
####  RADARR: Port 7878  ####

  radarr:
    image: ghcr.io/hotio/radarr:latest
    container_name: radarr
    environment:
      - PUID=[your PUID]
      - PGID=[your PGID]
      - TZ=[Your_timezone]
    volumes:
      - /path/to/your/config/folder:/config
      - /path/to/your/movie/files:/media/movies
      - /path/to/downloadclient-downloads:/downloads
    depends_on:
      - gluetun
    network_mode: "container:gluetun"
    restart: unless-stopped

#### LIDARR: Port 8686 ####

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=[your PUID]
      - PGID=[your PGID]
      - TZ=[Your_timezone]
    volumes:
      - /path/to/your/config/folder:/config
      - /path/to/your/music/files:/media/music #optional
      - /path/to/downloadclient-downloads:/downloads #optional
    depends_on:
      - gluetun
    network_mode: "container:gluetun"
    restart: unless-stopped
    
####  PROWLARR: Port 9696  ####

  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=[Your PUID]
      - PGID=[Your PGID]
      - TZ=[Your_timezone]
    volumes:
      - /path/to/your/config/folder:/config
    depends_on:
      - gluetun
    network_mode: "container:gluetun"
    restart: unless-stopped

### REQUESTRR: Port 4545 ###

  requestrr:
    image: darkalfx/requestrr
    container_name: requestrr
    depends_on:
      - gluetun
    network_mode: "container:gluetun"
    volumes:
    - /path/to/config/folder:/root/config
    restart: unless-stopped

networks:
  name_of_your_network (from the Gluetun config above):
    external: true
